"""Mandatory clause definitions — Thai law compliance baseline.

Every NDA (and optionally any contract) generated by EA-LIE must embed all
five mandatory clauses.  Tests assert presence of each TAG in every document.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MandatoryClause:
    id: str
    tag: str  # unique ASCII marker embedded in generated docs for test assertion
    title_en: str
    title_th: str
    text_en: str
    text_th: str


INJUNCTIVE_RELIEF = MandatoryClause(
    id="INJUNCTIVE_RELIEF_CCC213",
    tag="##MC:IR##",
    title_en="Injunctive Relief",
    title_th="การบังคับตามสิทธิ",
    text_en=(
        "The parties acknowledge that a breach of this Agreement may cause irreparable harm for "
        "which monetary damages would be an inadequate remedy.  Accordingly, either party shall be "
        "entitled to seek injunctive or other equitable relief pursuant to Section 213 of the Civil "
        "and Commercial Code of Thailand, without the requirement to post bond or other security, "
        "in addition to all other remedies available at law or in equity."
    ),
    text_th=(
        "คู่สัญญายอมรับว่าการละเมิดข้อตกลงนี้อาจก่อให้เกิดความเสียหายที่ไม่อาจเยียวยาได้ด้วยค่าเสียหายเป็นตัวเงิน "
        "ดังนั้น คู่สัญญาฝ่ายใดฝ่ายหนึ่งมีสิทธิขอให้ศาลมีคำสั่งห้ามหรือบังคับตามสิทธิตามมาตรา 213 "
        "แห่งประมวลกฎหมายแพ่งและพาณิชย์ของไทย โดยไม่จำเป็นต้องวางหลักประกัน "
        "นอกเหนือจากสิทธิและการเยียวยาอื่น ๆ ที่มีอยู่ตามกฎหมาย"
    ),
)

LD_THB10M = MandatoryClause(
    id="LD_THB10M",
    tag="##MC:LD##",
    title_en="Liquidated Damages",
    title_th="ค่าเสียหายที่กำหนดล่วงหน้า",
    text_en=(
        "In the event of a breach of this Agreement, the breaching party shall pay to the "
        "non-breaching party liquidated damages in the amount of not less than Thai Baht Ten Million "
        "(THB 10,000,000) per breach, which the parties agree represents a genuine pre-estimate of "
        "loss and is not a penalty.  This provision does not limit any other remedy available to "
        "the non-breaching party."
    ),
    text_th=(
        "ในกรณีที่มีการละเมิดข้อตกลงนี้ ฝ่ายที่ละเมิดต้องชำระค่าเสียหายที่กำหนดล่วงหน้าแก่ฝ่ายที่ไม่ได้ละเมิด "
        "ในจำนวนไม่น้อยกว่าสิบล้านบาทถ้วน (10,000,000 บาท) ต่อการละเมิดหนึ่งครั้ง "
        "ซึ่งคู่สัญญาตกลงว่าเป็นการประมาณการความสูญเสียล่วงหน้าที่สมเหตุสมผล และไม่ใช่ค่าปรับ "
        "บทบัญญัตินี้ไม่จำกัดสิทธิการเยียวยาอื่น ๆ ที่มีแก่ฝ่ายที่ไม่ได้ละเมิด"
    ),
)

PDPA_DPA_XREF = MandatoryClause(
    id="PDPA_DPA_XREF",
    tag="##MC:PDPA##",
    title_en="Personal Data Protection — DPA Cross-Reference",
    title_th="การคุ้มครองข้อมูลส่วนบุคคล — การอ้างอิง DPA",
    text_en=(
        "To the extent that either party processes personal data in connection with this Agreement, "
        "such processing shall be governed by the Data Processing Agreement (DPA) executed between "
        "the parties pursuant to the Personal Data Protection Act B.E. 2562 (PDPA) and its "
        "subordinate regulations.  In the event of conflict between this Agreement and the DPA, "
        "the DPA shall prevail with respect to personal data processing obligations."
    ),
    text_th=(
        "ในขอบเขตที่คู่สัญญาฝ่ายใดฝ่ายหนึ่งประมวลผลข้อมูลส่วนบุคคลที่เกี่ยวข้องกับข้อตกลงนี้ "
        "การประมวลผลดังกล่าวจะอยู่ภายใต้ข้อตกลงการประมวลผลข้อมูล (DPA) ที่ทำขึ้นระหว่างคู่สัญญา "
        "ตามพระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 (PDPA) และระเบียบที่เกี่ยวข้อง "
        "ในกรณีที่มีข้อขัดแย้งระหว่างข้อตกลงนี้กับ DPA ให้ DPA มีผลบังคับเหนือกว่าในส่วน "
        "ที่เกี่ยวกับพันธกรณีการประมวลผลข้อมูลส่วนบุคคล"
    ),
)

SEC_DISCLOSURE_CARVEOUT = MandatoryClause(
    id="SEC_DISCLOSURE_CARVEOUT",
    tag="##MC:SEC##",
    title_en="SEC Act Disclosure Carve-Out",
    title_th="ข้อยกเว้นการเปิดเผยข้อมูลตามพระราชบัญญัติหลักทรัพย์ฯ",
    text_en=(
        "Notwithstanding any confidentiality obligations herein, either party may disclose "
        "Confidential Information to the extent required by the Securities and Exchange Act "
        "B.E. 2535 (as amended), the Securities and Exchange Commission of Thailand, or any "
        "other governmental or regulatory authority having jurisdiction, provided that the "
        "disclosing party shall: (i) provide the other party with prior written notice as soon "
        "as practicable; (ii) cooperate with the other party in seeking a protective order or "
        "other confidential treatment; and (iii) disclose only that portion of Confidential "
        "Information legally required to be disclosed."
    ),
    text_th=(
        "แม้จะมีข้อผูกพันด้านการรักษาความลับใด ๆ ในที่นี้ คู่สัญญาฝ่ายใดฝ่ายหนึ่งอาจเปิดเผยข้อมูลลับ "
        "เท่าที่กำหนดโดยพระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535 (ที่แก้ไขเพิ่มเติม) "
        "สำนักงาน ก.ล.ต. หรือหน่วยงานภาครัฐหรือหน่วยงานกำกับดูแลอื่นที่มีเขตอำนาจ "
        "โดยฝ่ายที่เปิดเผยต้อง: (i) แจ้งให้อีกฝ่ายทราบเป็นลายลักษณ์อักษรล่วงหน้าโดยเร็วที่สุด "
        "เท่าที่เป็นไปได้; (ii) ให้ความร่วมมือกับอีกฝ่ายในการขอคำสั่งคุ้มครอง; และ "
        "(iii) เปิดเผยเฉพาะส่วนของข้อมูลลับที่กฎหมายกำหนดให้ต้องเปิดเผย"
    ),
)

ESIGNATURE_THAI = MandatoryClause(
    id="ESIGNATURE_THAI",
    tag="##MC:ESIG##",
    title_en="Electronic Signature",
    title_th="ลายมือชื่ออิเล็กทรอนิกส์",
    text_en=(
        "The parties agree that this Agreement may be executed by electronic signature in "
        "accordance with the Electronic Transactions Act B.E. 2544 (as amended) and the "
        "Ministerial Regulations thereunder.  An electronic signature shall have the same legal "
        "force and effect as a handwritten signature.  Each party represents that the person "
        "executing this Agreement on its behalf has full authority to bind such party."
    ),
    text_th=(
        "คู่สัญญาตกลงว่าข้อตกลงนี้อาจลงนามโดยลายมือชื่ออิเล็กทรอนิกส์ตามพระราชบัญญัติว่าด้วยธุรกรรม "
        "ทางอิเล็กทรอนิกส์ พ.ศ. 2544 (ที่แก้ไขเพิ่มเติม) และกฎกระทรวงที่เกี่ยวข้อง "
        "ลายมือชื่ออิเล็กทรอนิกส์มีผลทางกฎหมายและผลบังคับเท่ากับลายมือชื่อที่เขียนด้วยลายมือ "
        "คู่สัญญาแต่ละฝ่ายรับรองว่าบุคคลที่ลงนามในข้อตกลงนี้มีอำนาจเต็มในการผูกพันฝ่ายนั้น"
    ),
)

ALL_MANDATORY_CLAUSES: list[MandatoryClause] = [
    INJUNCTIVE_RELIEF,
    LD_THB10M,
    PDPA_DPA_XREF,
    SEC_DISCLOSURE_CARVEOUT,
    ESIGNATURE_THAI,
]

MANDATORY_CLAUSE_TAGS: set[str] = {c.tag for c in ALL_MANDATORY_CLAUSES}
MANDATORY_CLAUSE_IDS: list[str] = [c.id for c in ALL_MANDATORY_CLAUSES]
