"""Contract drafter — 6 types.  Sensitive text generated by qwen3-8b ON-PREM via
LM Studio (localhost:1234).  Never sends contract content to cloud APIs.
"""
from __future__ import annotations

import io
import logging
import sys
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "shared"))
from lmstudio_client import PRIMARY_MODEL, chat_complete  # noqa: E402

logger = logging.getLogger(__name__)


class ContractType(str, Enum):
    NDA = "nda"
    SERVICE_AGREEMENT = "service_agreement"
    EMPLOYMENT = "employment"
    LICENSE = "license"
    CONSTRUCTION = "construction"
    PARTNERSHIP = "partnership"


_SECTIONS: dict[ContractType, list[str]] = {
    ContractType.NDA: [
        "definitions",
        "confidentiality_obligations",
        "permitted_disclosures",
        "exclusions_from_confidentiality",
        "term_and_termination",
        "return_of_information",
        "remedies",
        "general_provisions",
    ],
    ContractType.SERVICE_AGREEMENT: [
        "scope_of_services",
        "fees_and_payment_schedule",
        "intellectual_property_ownership",
        "warranties_and_representations",
        "liability_limitation",
        "term_and_termination",
        "general_provisions",
    ],
    ContractType.EMPLOYMENT: [
        "position_and_duties",
        "compensation_and_benefits",
        "working_hours_and_leave",
        "confidentiality_and_ip_assignment",
        "non_compete_and_non_solicitation",
        "termination_and_severance",
        "general_provisions",
    ],
    ContractType.LICENSE: [
        "grant_of_license",
        "license_restrictions",
        "royalties_and_payments",
        "intellectual_property_and_ownership",
        "warranties_and_indemnification",
        "term_and_termination",
        "general_provisions",
    ],
    ContractType.CONSTRUCTION: [
        "scope_of_works",
        "contract_price_and_payment",
        "program_and_time_for_completion",
        "variations_and_adjustments",
        "testing_and_commissioning",
        "defects_liability",
        "claims_and_disputes",
        "general_provisions",
    ],
    ContractType.PARTNERSHIP: [
        "business_purpose_and_name",
        "capital_contributions",
        "profit_and_loss_allocation",
        "management_and_decision_making",
        "transfer_of_partnership_interests",
        "dissolution_and_winding_up",
        "general_provisions",
    ],
}


@dataclass
class DraftResult:
    contract_type: ContractType
    sections: dict[str, str]
    docx_bytes: bytes


class ContractDrafter:
    """Drafts contracts using qwen3-8b on-prem for all sensitive content."""

    def __init__(self, lmstudio_base: str = "http://localhost:1234") -> None:
        self._base = lmstudio_base

    def draft(self, contract_type: ContractType, context: dict[str, Any]) -> DraftResult:
        """Generate contract sections with qwen3-8b, then build docx."""
        sections = self._generate_sections(contract_type, context)
        docx_bytes = self._build_docx(contract_type, context, sections)
        return DraftResult(
            contract_type=contract_type,
            sections=sections,
            docx_bytes=docx_bytes,
        )

    # ------------------------------------------------------------------

    def _generate_sections(
        self, contract_type: ContractType, context: dict[str, Any]
    ) -> dict[str, str]:
        section_names = _SECTIONS[contract_type]
        results: dict[str, str] = {}
        for section in section_names:
            results[section] = self._generate_section(contract_type, section, context)
        return results

    def _generate_section(
        self,
        contract_type: ContractType,
        section: str,
        context: dict[str, Any],
    ) -> str:
        ctx_summary = ", ".join(f"{k}={v}" for k, v in list(context.items())[:6])
        prompt = (
            f"Draft the '{section.replace('_', ' ').title()}' section for a Thai-law "
            f"{contract_type.value.replace('_', ' ').title()} contract.\n"
            f"Context: {ctx_summary}\n"
            f"Requirements: bilingual EN/TH, legally precise, suitable for Thai jurisdiction. "
            f"Output the section text only, no headings."
        )
        try:
            return chat_complete(prompt, model=PRIMARY_MODEL)
        except Exception as exc:
            logger.error("qwen3 section '%s' failed: %s", section, exc)
            return f"[Section '{section}' generation failed — manual drafting required]"

    def _build_docx(
        self,
        contract_type: ContractType,
        context: dict[str, Any],
        sections: dict[str, str],
    ) -> bytes:
        doc = Document()

        title = contract_type.value.replace("_", " ").upper()
        h = doc.add_heading(title, level=1)
        h.alignment = WD_ALIGN_PARAGRAPH.CENTER

        parties_en = context.get("parties_en", "")
        parties_th = context.get("parties_th", "")
        if parties_en or parties_th:
            doc.add_heading("PARTIES / คู่สัญญา", level=2)
            doc.add_paragraph(f"{parties_en}\n{parties_th}".strip())

        for section_key, content in sections.items():
            heading = section_key.replace("_", " ").title()
            doc.add_heading(heading, level=2)
            doc.add_paragraph(content)

        buf = io.BytesIO()
        doc.save(buf)
        return buf.getvalue()
