import type {
  AnomalyRecord,
  AuditEntry,
  DocumentRecord,
  LieReview,
  ObligationRecord,
  PipPackageScore,
} from "../types";

export const mockData = {
  documents: [
    {
      id: 41,
      filename: "EPC-Milestone-04-TAC.pdf",
      doc_type: "DOC-06",
      confidence: 0.94,
      status: "INDEXED",
      page_count: 18,
      created_at: "2026-06-14T02:20:00+07:00",
    },
    {
      id: 42,
      filename: "JV-IP-Annex-B.pdf",
      doc_type: "DOC-05",
      confidence: 0.82,
      status: "PENDING_REVIEW",
      page_count: 33,
      created_at: "2026-06-14T03:05:00+07:00",
    },
    {
      id: 43,
      filename: "Supplier-DPA-Thai.pdf",
      doc_type: "DOC-09",
      confidence: 0.91,
      status: "INDEXED",
      page_count: 12,
      created_at: "2026-06-13T17:35:00+07:00",
    },
  ] satisfies DocumentRecord[],
  obligations: [
    {
      id: 7,
      document_id: 41,
      description: "CTO TAC signature required before milestone drawdown",
      due_date: "2026-06-17",
      responsible_party: "CTO",
      status: "OPEN",
    },
    {
      id: 8,
      document_id: 43,
      description: "PDPA subprocessors list to be attached",
      due_date: "2026-06-21",
      responsible_party: "Legal",
      status: "OPEN",
    },
  ] satisfies ObligationRecord[],
  anomalies: [
    {
      id: 91,
      entity_type: "invoice",
      entity_id: 5204,
      score: 0.91,
      features: { reason: "Price variance above tolerance", delta_bps: 620 },
    },
    {
      id: 92,
      entity_type: "payment",
      entity_id: 118,
      score: 0.74,
      features: { reason: "Payment requested before TAC", blocked: true },
    },
  ] satisfies AnomalyRecord[],
  fciAudit: [
    {
      id: 316,
      entity_type: "payment",
      entity_id: 118,
      action: "initiate",
      actor: "cfo",
      entry_hash: "9bc2f0a7f63d",
      created_at: "2026-06-14T04:12:00+07:00",
    },
    {
      id: 315,
      entity_type: "tac_certificate",
      entity_id: 44,
      action: "esign_complete",
      actor: "cto",
      entry_hash: "7a1e80cf2a9b",
      created_at: "2026-06-14T03:48:00+07:00",
    },
  ] satisfies AuditEntry[],
  packageScores: [
    {
      bid_id: 141,
      evaluator_id: "eval-a",
      weighted_total: 88,
      is_outlier: false,
      z_score: 0.18,
    },
    {
      bid_id: 144,
      evaluator_id: "eval-b",
      weighted_total: 63,
      is_outlier: true,
      z_score: 2.41,
    },
    {
      bid_id: 147,
      evaluator_id: "eval-c",
      weighted_total: 79,
      is_outlier: false,
      z_score: 0.74,
    },
  ] satisfies PipPackageScore[],
  pipAudit: [
    {
      id: 210,
      entity_type: "bid",
      entity_id: 144,
      action: "evaluation_submitted",
      actor: "eval-b",
      entry_hash: "c61845c4190e",
      created_at: "2026-06-14T02:44:00+07:00",
    },
    {
      id: 209,
      entity_type: "package",
      entity_id: 18,
      action: "qa_broadcast",
      actor: "api",
      entry_hash: "6541b00af87a",
      created_at: "2026-06-13T18:11:00+07:00",
    },
  ] satisfies AuditEntry[],
  lieReviews: [
    {
      contract_id: "LIE-104",
      title: "EPC Framework Amendment",
      score: 72,
      rag: "RED",
      reviewer_level: "EXTERNAL_LAWYER",
      gaps: ["MISSING: SEC Act Disclosure Carve-Out", "LD amount below threshold"],
      due_date: "2026-06-18",
    },
    {
      contract_id: "LIE-107",
      title: "Supplier NDA Renewal",
      score: 34,
      rag: "AMBER",
      reviewer_level: "LEGAL_COUNSEL",
      gaps: ["MISSING: Thai E-Signature Block"],
      due_date: "2026-06-24",
    },
    {
      contract_id: "LIE-112",
      title: "DPA Cross-Border Addendum",
      score: 18,
      rag: "GREEN",
      reviewer_level: "CTO_CFO",
      gaps: [],
      due_date: "2026-07-01",
    },
  ] satisfies LieReview[],
};
